### ISSUE TITLE
Accessing Flip Card image_uris() attribute

### ISSUE THREAD

**Issue by closejj** [NandaScott/Scrython#13]
Requesting the image urls for a flip card (e.g. "Garruk Relentless // Garruk, the Veil-Cursed") results in a KeyError:

```
card = scrython.cards.Named(exact='Garruk Relentless // Garruk, the Veil-Cursed')
card.image_uris()

```
 >>>KeyError: "This card has no key 'image_uris'"

It appears that image_uris appears in the card object, but I'm not sure how to access it.

**Comment by NandaScott** [comment]
Ah, this is because the image uris are in the `card_faces` dictionary in the card object. You can access the face with `card.card_faces(0)['image_uris']` to get that dictionary. There's not a great way I can think of to add that kind of functionality without needlessly over complicating the amount of methods available.
