### ISSUE TITLE
Card Sets

### ISSUE THREAD

**Issue by The-Duchess** [NandaScott/Scrython#28]
the library pulls cards not by set but by a query that returns a single card making the ability to pull price information accurately, and for practical use, difficult. the workaround for the issues presented by this seems to require the crude slamming of full set lists for cards through multiple contrived queries that are just wrappers on the API.

so the affected issues are: getting the price info has been made essentially impossible due to structure and getting a card by set is also similarly clunky and requires use of external resources such as mtgsdk.

**Comment by NandaScott** [comment]
I'm not entirely sure what the issue is, can you give me an example of what you're doing?

If you want to get a card from a single set you can do:
`card = scrython.cards.Named(fuzzy='Lightning Bolt', set='M11')`
Then
`card.currency('usd')`
`card.currency('eur')`
`card.currency('tix')`
For the prices, when available.

The `.currency()` method is available through all `cards` classes.
